%downloadAssets Download Fiscal.ai binary assets.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(fullfile(projectRoot, "src"));

client = fiscalai.FiscalAIClient(EnvFile=fullfile(projectRoot, ".env"));

client.companyLogo( ...
    CompanyKey="NASDAQ_MSFT", ...
    Variant="logo", ...
    OutputFile=fullfile(tempdir, "msft-logo.png"));

client.filingPdf( ...
    "0000320193-24-000123", ...
    Ticker="AAPL", ...
    Exchange="NASDAQ", ...
    OutputFile=fullfile(tempdir, "aapl-filing.pdf"));
