%earningsCalendarWorkflow Inspect upcoming earnings events.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(fullfile(projectRoot, "src"));

client = fiscalai.FiscalAIClient( ...
    EnvFile=fullfile(projectRoot, ".env"), NormalizeTypes=true);
today = datetime("today");
events = client.earningsCalendar( ...
    Tickers="MSFT", ...
    DateFrom=string(today, "yyyy-MM-dd"), ...
    DateTo=string(today + caldays(60), "yyyy-MM-dd"), ...
    PageSize=25, ...
    DateSort="date:asc");

if istable(events) && height(events) > 0
    columns = intersect(["date", "ticker", "name", "period", "epsEst", ...
        "revenueEst", "importance"], string(events.Properties.VariableNames), "stable");
    disp(events(:, columns))
else
    disp(events)
end
