function snapshot = companySnapshot(client, options)
%companySnapshot Pull a compact multi-endpoint company snapshot.

    arguments
        client (1,1) fiscalai.FiscalAIClient
        options.Ticker = []
        options.MicCode = []
        options.Exchange = []
        options.CompanyKey = []
        options.Cusip = []
        options.Isin = []
        options.Figi = []
        options.Cik = []
        options.PeriodType = "annual"
        options.Currency = []
        options.PriceStartDate = []
        options.PriceEndDate = []
        options.RatioIds (1,:) string = [ ...
            "ratio_price_to_earnings", ...
            "ratio_price_to_sales", ...
            "ratio_ev_to_ebitda"]
        options.IncludePrices (1,1) logical = true
        options.IncludeEarnings (1,1) logical = true
    end

    identifierArgs = namedargs2cell(struct( ...
        "Ticker", options.Ticker, ...
        "MicCode", options.MicCode, ...
        "Exchange", options.Exchange, ...
        "CompanyKey", options.CompanyKey, ...
        "Cusip", options.Cusip, ...
        "Isin", options.Isin, ...
        "Figi", options.Figi, ...
        "Cik", options.Cik));
    statementArgs = [identifierArgs, { ...
        "PeriodType", options.PeriodType, ...
        "Currency", options.Currency, ...
        "ReturnType", "timetable"}];

    profileArgs = [identifierArgs, {"ReturnType", "struct"}];
    profile = client.companyProfile(profileArgs{:});
    income = client.standardizedFinancials("income-statement", statementArgs{:});
    balanceSheet = client.standardizedFinancials("balance-sheet", statementArgs{:});
    cashFlow = client.standardizedFinancials("cash-flow-statement", statementArgs{:});

    companyId = snapshotCompanyId(profile, options);
    ratios = fiscalai.workflows.valuationScreen( ...
        client, companyId, Identifier="CompanyKey", ...
        RatioIds=options.RatioIds, PeriodType=options.PeriodType, ...
        Currency=options.Currency);

    prices = timetable();
    if options.IncludePrices
        priceArgs = [identifierArgs, { ...
            "StartDate", options.PriceStartDate, ...
            "EndDate", options.PriceEndDate, ...
            "ReturnType", "timetable"}];
        prices = client.stockPrices(priceArgs{:});
    end

    earnings = table();
    if options.IncludeEarnings
        earningsArgs = [identifierArgs, {"ReturnType", "table"}];
        earnings = client.earningsSummary(earningsArgs{:});
    end

    snapshot = struct( ...
        "Profile", profile, ...
        "IncomeStatement", income.data, ...
        "BalanceSheet", balanceSheet.data, ...
        "CashFlowStatement", cashFlow.data, ...
        "ValuationRatios", ratios, ...
        "StockPrices", prices, ...
        "EarningsSummary", earnings);
end

function companyId = snapshotCompanyId(profile, options)
    if ~isempty(options.CompanyKey)
        companyId = string(options.CompanyKey);
    elseif isfield(profile, "exchangeSymbol") && isfield(profile, "ticker")
        companyId = string(profile.exchangeSymbol) + "_" + string(profile.ticker);
    elseif isfield(profile, "ticker")
        companyId = string(profile.ticker);
    else
        error("fiscalai:WorkflowMissingCompanyId", ...
            "Provide CompanyKey or a profile response with ticker fields.");
    end
end
