function outputFile = generateMethodDocs(outputFile)
%generateMethodDocs Generate concise public method help documentation.

    arguments
        outputFile (1,1) string = fullfile( ...
            fileparts(fileparts(mfilename("fullpath"))), "docs", "METHOD_HELP.md")
    end

    outputFolder = fileparts(outputFile);
    if ~isfolder(outputFolder)
        mkdir(outputFolder);
    end

    catalog = methodCatalog();
    lines = strings(6 + 7 * height(catalog), 1);
    cursor = 1;
    lines(cursor) = "# FiscalAIClient Method Help"; cursor = cursor + 1;
    lines(cursor) = ""; cursor = cursor + 1;
    lines(cursor) = "Generated by `tools/generateMethodDocs.m`. Keep method signatures and endpoint notes in that generator."; cursor = cursor + 1;
    lines(cursor) = ""; cursor = cursor + 1;
    lines(cursor) = "Default responses use `ReturnType=""auto""`. Pass `ReturnType=""struct""` for raw JSON-derived data or `ReturnType=""table""` to require table conversion."; cursor = cursor + 1;
    lines(cursor) = ""; cursor = cursor + 1;

    for idx = 1:height(catalog)
        endpoint = catalog.Endpoint(idx);
        if strlength(endpoint) == 0
            endpoint = "N/A";
        end
        lines(cursor) = "## `" + catalog.Method(idx) + "`"; cursor = cursor + 1;
        lines(cursor) = ""; cursor = cursor + 1;
        lines(cursor) = "- Syntax: `" + catalog.Syntax(idx) + "`"; cursor = cursor + 1;
        lines(cursor) = "- Endpoint: `" + endpoint + "`"; cursor = cursor + 1;
        lines(cursor) = "- Returns: " + catalog.Returns(idx); cursor = cursor + 1;
        lines(cursor) = "- Notes: " + catalog.Notes(idx); cursor = cursor + 1;
        lines(cursor) = ""; cursor = cursor + 1;
    end

    writelines(lines, outputFile);
end

function catalog = methodCatalog()
    method = [
        "FiscalAIClient"
        "request"
        "companiesList"
        "companyProfile"
        "companyLogo"
        "companyNews"
        "asReportedIncomeStatement"
        "asReportedBalanceSheet"
        "asReportedCashFlowStatement"
        "standardizedIncomeStatement"
        "standardizedBalanceSheet"
        "standardizedCashFlowStatement"
        "standardizedMetricsList"
        "allStandardizedMetricsList"
        "ratiosList"
        "companyRatios"
        "dailyRatios"
        "sharesOutstanding"
        "adjustedMetrics"
        "adjustedNumbers"
        "segmentsAndKpis"
        "stockSplits"
        "stockPrices"
        "intradayStockPrices"
        "companyFilings"
        "filingImage"
        "filingPdf"
        "earningsCalendar"
        "earningsSummary"];
    syntax = [
        "client = fiscalai.FiscalAIClient(ApiKey=..., NormalizeTypes=true)"
        "data = client.request(""/v1/path"", Query=struct(...))"
        "data = client.companiesList(PageNumber=1, PageSize=1000)"
        "profile = client.companyProfile(CompanyKey=""NASDAQ_MSFT"")"
        "[bytes, metadata] = client.companyLogo(CompanyKey=""NASDAQ_MSFT"", Variant=""logo"")"
        "news = client.companyNews(CompanyKey=""NASDAQ_MSFT"", StartDate=""2026-01-01"")"
        "data = client.asReportedIncomeStatement(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.asReportedBalanceSheet(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.asReportedCashFlowStatement(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.standardizedIncomeStatement(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.standardizedBalanceSheet(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.standardizedCashFlowStatement(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "metrics = client.standardizedMetricsList(""standard"", ""income-statement"")"
        "metrics = client.allStandardizedMetricsList()"
        "ratios = client.ratiosList()"
        "data = client.companyRatios(CompanyKey=""NASDAQ_MSFT"", RatioId=""ratio_price_to_earnings"")"
        "data = client.dailyRatios(""ratio_price_to_earnings"", CompanyKey=""NASDAQ_MSFT"")"
        "data = client.sharesOutstanding(CompanyKey=""NASDAQ_MSFT"")"
        "data = client.adjustedMetrics(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.adjustedNumbers(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "data = client.segmentsAndKpis(CompanyKey=""NASDAQ_MSFT"", PeriodType=""annual"")"
        "splits = client.stockSplits(CompanyKey=""NASDAQ_MSFT"")"
        "prices = client.stockPrices(CompanyKey=""NASDAQ_MSFT"", StartDate=""2026-01-01"")"
        "prices = client.intradayStockPrices(CompanyKey=""NASDAQ_MSFT"", StartDate=""2026-01-01"")"
        "filings = client.companyFilings(CompanyKey=""NASDAQ_MSFT"")"
        "[bytes, metadata] = client.filingImage(filingId, 1, CompanyKey=""NASDAQ_MSFT"")"
        "[bytes, metadata] = client.filingPdf(filingId, CompanyKey=""NASDAQ_MSFT"")"
        "events = client.earningsCalendar(Tickers=""MSFT"", PageSize=25)"
        "summary = client.earningsSummary(CompanyKey=""NASDAQ_MSFT"")"];
    endpoint = [
        ""
        "Any GET path"
        "/v2/companies-list"
        "/v2/company/profile"
        "/v2/company/logo"
        "/v1/company/news"
        "/v1/company/financials/income-statement/as-reported"
        "/v1/company/financials/balance-sheet/as-reported"
        "/v1/company/financials/cash-flow-statement/as-reported"
        "/v1/company/financials/income-statement/standardized"
        "/v1/company/financials/balance-sheet/standardized"
        "/v1/company/financials/cash-flow-statement/standardized"
        "/v1/standardized-metrics-list/{templateType}/{statementType}"
        "/v1/standardized-metrics-list"
        "/v1/ratios-list"
        "/v1/company/ratios"
        "/v1/company/ratios/daily/{ratioId}"
        "/v1/company/shares-outstanding"
        "/v1/company/adjusted-metrics"
        "/v1/company/adjusted-numbers"
        "/v2/company/segments-and-kpis"
        "/v1/company/stock-splits"
        "/v2/company/stock-prices"
        "/v1/company/stock-prices/intraday"
        "/v2/company/filings"
        "/v1/filing/{filingId}/page/{pageNumber}/image"
        "/v1/filing/{filingId}/pdf"
        "/v1/calendar/earnings"
        "/v1/company/earnings-summary"];
    returns = [
        "A configured `FiscalAIClient` object."
        "Auto-converted table/struct data for an arbitrary Fiscal.ai GET endpoint."
        "Paged company catalog; auto mode returns `data` as a table."
        "Company profile struct by default."
        "Image bytes and response metadata; writes to `OutputFile` when supplied."
        "News event data filtered by identifiers and dates."
        "As-reported financial statement data."
        "As-reported balance sheet data."
        "As-reported cash flow data."
        "Standardized income statement with period rows and metric columns."
        "Standardized balance sheet with period rows and metric columns."
        "Standardized cash flow statement with period rows and metric columns."
        "Metric catalog for one reporting template and statement."
        "Complete standardized metric catalog."
        "Ratio catalog table."
        "Company ratio periods with metric columns in auto mode."
        "Daily values for one ratio."
        "Shares outstanding payload."
        "Adjusted metrics payload."
        "Adjusted numbers payload."
        "Segments and KPI payload."
        "Stock split history."
        "Daily stock price table in auto mode."
        "Intraday price payload."
        "Filings table in auto mode."
        "Image bytes and metadata."
        "PDF bytes and metadata."
        "Earnings events table in auto mode."
        "Latest earnings summary payload."];
    notes = [
        "API key resolution order is explicit `ApiKey`, MATLAB Vault, environment variable, then `.env`."
        "Use this when Fiscal.ai adds an endpoint before a wrapper is available."
        "Use paging for large catalog reads."
        "Use `ReturnType=""struct""` for raw profile fields."
        "Supported variants include `icon`, `logo`, and `logo-dark`."
        "Supports `StartDate`, `EndDate`, `EventType`, and `Importance`."
        "Accepts standard company identifiers plus `PeriodType` and `Currency`."
        "Accepts standard company identifiers plus `PeriodType` and `Currency`."
        "Accepts standard company identifiers plus `PeriodType` and `Currency`."
        "Enable `NormalizeTypes=true` to convert date-like fields to `datetime`."
        "Enable `NormalizeTypes=true` to convert date-like fields to `datetime`."
        "Enable `NormalizeTypes=true` to convert date-like fields to `datetime`."
        "Path values are URL encoded."
        "Useful for discovering available metric IDs."
        "Useful for discovering `RatioId` values."
        "Use `RatioId` to request one ratio family."
        "Pass the ratio ID as the first positional argument."
        "Returns the Fiscal.ai payload without endpoint-specific flattening."
        "Returns adjusted metrics using Fiscal.ai schema."
        "Alias endpoint retained for compatibility."
        "Uses the v2 endpoint; `legacySegmentsAndKpis` is also available."
        "Returns split records for the selected company."
        "Use `Latest=true` for only the latest price."
        "Use date filters to limit response size."
        "Rows may have optional fields; auto mode handles missing values as empty cells."
        "Use `OutputFile` to persist the image."
        "Use `OutputFile` to persist the PDF."
        "Supports ticker lists, date filters, paging, sort, and importance."
        "Returns the latest company earnings summary."];

    catalog = table(method, syntax, endpoint, returns, notes, ...
        VariableNames=["Method", "Syntax", "Endpoint", "Returns", "Notes"]);
end
